#' Manifest Schemas (R to JS Contract)
#'
#' shinyelectron generates three JSON manifest files at build time that
#' the Electron runtime reads on the end user's machine. These are the
#' de-facto API contract between R and JavaScript.
#'
#' Each manifest carries a `schema_version` field (the
#' `MANIFEST_SCHEMA_VERSION` constant in R, mirrored in
#' `inst/electron/backends/utils.js`). The JS side warns on mismatch
#' rather than crashing, so older apps can keep running after a
#' schema bump.
#'
#' ## dependencies.json
#' Generated by [generate_dependency_manifest()]. Consumed by
#' `inst/electron/backends/dependency-checker.js`. Describes the
#' packages an app needs at runtime.
#'
#' ```json
#' {
#'   "schema_version": "2",
#'   "language": "r" | "python",
#'   "packages": ["shiny", "bslib", ...],
#'   "binary_only": true,
#'   "repos": ["https://cloud.r-project.org"],       // R only
#'   "index_urls": ["https://pypi.org/simple"],      // Python only
#'   "system_deps": {                                 // optional, R only
#'     "debian": ["libcurl4-openssl-dev", ...],
#'     "fedora": ["libcurl-devel", ...]
#'   }
#' }
#' ```
#'
#' ## runtime-manifest.json
#' Generated by [generate_runtime_manifest()] (R) and
#' [generate_python_runtime_manifest()] (Python). Consumed by
#' `inst/electron/backends/runtime-downloader.js`. Tells the auto-download
#' strategy where to fetch the runtime.
#'
#' ```json
#' {
#'   "schema_version": "2",
#'   "language": "r" | "python",
#'   "version": "4.5.3",
#'   "download_url": "https://...",
#'   "install_path": "~/.shinyelectron/runtimes/R-4.5.3",
#'   "platform": "win" | "mac" | "linux",
#'   "arch": "x64" | "arm64",
#'   "sha256": "..."                                  // optional
#' }
#' ```
#'
#' ## apps-manifest.json
#' Generated by [export_multi_app()]. Consumed by
#' `inst/electron/shared/main.js`. Drives the multi-app launcher UI.
#'
#' ```json
#' {
#'   "schema_version": "2",
#'   "default_type": "r-shiny",
#'   "runtime_strategy": "auto-download",
#'   "apps": [
#'     {
#'       "id": "dashboard",
#'       "name": "Dashboard",
#'       "description": "...",
#'       "type": "r-shiny",
#'       "runtime_strategy": "auto-download",
#'       "icon": null,
#'       "serve": { "kind": "native", "path": "src/apps/dashboard", "runtime_strategy": "auto-download" }
#'     },
#'     {
#'       "id": "viewer",
#'       "name": "Viewer",
#'       "description": "...",
#'       "type": "r-shiny",
#'       "runtime_strategy": "shinylive",
#'       "icon": null,
#'       "serve": { "kind": "shinylive", "site": "src/shinylive-site", "subdir": "viewer" }
#'     },
#'     {
#'       "id": "boxed",
#'       "name": "Boxed",
#'       "description": "...",
#'       "type": "r-shiny",
#'       "runtime_strategy": "container",
#'       "icon": null,
#'       "serve": { "kind": "container", "path": "src/apps/boxed" }
#'     }
#'   ]
#' }
#' ```
#'
#' @name manifest-schemas
#' @keywords internal
NULL
